<?php

namespace App\Model;

use Doctrine\ORM\EntityRepository;

/**
 * PullRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PullRequestRepository extends EntityRepository
{
}
